### GENERAL SETTINGS ###

# Site settings
title: Hannah Haberkern
description: "Personal website of Hannah Haberkern"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://hannahhaberkern.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#ddb388" #"#00b3fe" #"#F70031"
  primary_rgb: "221,179,136" #"0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#46b9b9" #"#384452" #"#33004D"
  link: "#98b380" #"#a5bc8f" #"#428bca"
  link_hover: "#cfdf9f" #"#9d94b8" #"#cfdf9f" #"#01b2fe"
  footer_heading: "#f9f9ec" #"#ffffff"
  footer_content: "#ffffff" #"#bfc9d3"
  paragraph: "#666"
  navlink: "#cfdf9f"
  navact: "#e6e698" #"#ddb388" #
  button: "#ffffff"
  buttonborder: "#46b9b9"
  buttonhover: "rgba(221,179,136,0.3)" #"#98b380"
  buttonact: "rgba(221,179,136,0.8)" #"#98b380"
  buttonborderact: "rgb(221,179,136)" #"#a5bc8f"
  panelfill: "#e6e698"


# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/hjmh
  - title: linkedin
    url: https://www.linkedin.com/in/hannah-haberkern-24a73483
#  - title: scholar
#    url: https://scholar.google.com/citations?user=rTECIQwAAAAJ&hl=en&oi=ao


# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Janelia Research Campus
    - 20147 Ashburn
    - United States
email: haberkernh-at-janelia.hhmi.org
#tel: +34 8493-4893


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Mark Webber
    position: CEO
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Paul Jameson
    position: Lead Designer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Hi, I'm Hannah. I'm a neuroscientist trying to understand how animals
navigate through space.
If I'm not in the lab or analysing data, I like to travel, sew, garden or observe animals."

# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
    author: Marcel Newman
    position: WEB DESIGNER - BLACKTIE.CO
