### GENERAL SETTINGS ###

# Site settings
title: Hannah Haberkern
description: "Personal website of Hannah Haberkern"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://hannahhaberkern.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#70a5a9" #"#eabf95"
  primary_rgb: "112, 165, 169" #"234, 191, 149" #rgb of the primary. Needed in some places for the transparency effect.
  secondary:  "#394e60" #"#6aafaf"
  secondary_rgb: "57, 78, 96"
  link: "#bd5a28" #"#d18c47"
  link_hover: "#ffaa80" #"#ebccad"
  footer_heading: "#ffffff"
  footer_content: "#ffffff"
  paragraph: "#666"
  navlink: "#ffccb3" #"#f9e6d2"
  navact: "#ffaa80" #"#f4cda4"
  button: "#ffffff"
  buttonborder: "#394e60" #"#6aafaf"
  buttonhover: "rgba(235, 126, 71,0.7)" #"#eb7e47" #"rgba(221,179,136,0.3)"
  buttonact: "rgba(207, 84, 23,0.6)" #"rgba(221,179,136,0.8)"
  buttonborderact: "rgba(207, 84, 23,0.7)" #"rgb(221,179,136)"
  panelfill: "#568c8f" #"#ddb388"
  paneltext: "#fcefe8" #"#75a3a3"


# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/hjmh
  - title: linkedin
    url: https://www.linkedin.com/in/hannah-haberkern-24a73483
  - title: scholar
    url: https://scholar.google.com/citations?user=rTECIQwAAAAJ&hl=en&oi=ao


# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Janelia Research Campus
    - 20147 Ashburn
    - United States
email: haberkernh-at-janelia.hhmi.org
#tel: +34 8493-4893


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Mark Webber
    position: CEO
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Paul Jameson
    position: Lead Designer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Hi, I'm Hannah. I'm a neuroscientist interested in understanding animal behavior,
in particular in the context of navigation. If I'm not in the lab or analysing data,
I like to sew, program, garden or observe animals."

# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "Douter de tout ou tout croire, ce sont deux solutions également commodes, qui l'une et l'autre nous dispensent de réfléchir."
    message2: "To doubt everything, or, to believe everything, are two equally convenient solutions; both dispense with the necessity of reflection."
    author: Henri Poincare
    source: "La Science et l'Hypothèse, English translation: Science and Hypothesis (1905)"
