### GENERAL SETTINGS ###

# Site settings
title: Hannah Haberkern
description: "Personal website of Hannah Haberkern"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://hjmh.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#70a5a9"
  primary_rgb: "112, 165, 169"  #rgb of the primary. Needed in some places for the transparency effect.
  secondary:  "#304150"
  secondary_rgb: "48, 65, 80"
  link: "#bd5a28"
  link_hover: "#ffaa80"
  footer_heading: "#ffffff"
  footer_content: "#ffffff"
  paragraph: "#666"
  navlink: "#ffccb3" #"#f9e6d2"
  navact: "#ffaa80" #"#f4cda4"
  button: "#ffffff"
  buttonborder: "#394e60" #"#6aafaf"
  buttonhover: "rgba(235, 126, 71,0.7)"
  buttonact: "rgba(207, 84, 23,0.6)"
  buttonborderact: "rgba(207, 84, 23,0.7)"
  panelfill: "#568c8f"
  paneltext: "#fcefe8"


# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/hjmh
  - title: linkedin
    url: https://www.linkedin.com/in/hannah-haberkern-24a73483
  - title: instagram
    url: https://www.instagram.com/verdigrissewing
  - title: twitter
    url: https://twitter.com/HannahHaberkern
  - title: scholar
    url: https://scholar.google.com/citations?user=rTECIQwAAAAJ&hl=en&oi=ao

blogurl: "https://sendthoughtsintothevoid.com/"

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Janelia Research Campus
    - 20147 Ashburn
    - United States
email: haberkernh (at) janelia.hhmi.org
#tel: +34 8493-4893


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Hi, I'm Hannah. I'm a neuroscientist interested in understanding (neural) mechanisms
underlying animal behavior. If I'm not in the lab or analysing data,
I like to sew, garden or observe animals."
